# Generated by Django 4.2.4 on 2023-09-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userregistration', '0003_remove_userprofile_expertise_delete_expertise_and_more'),
        ('book_appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_appointment.appointment')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='userregistration.userprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userregistration.userprofile')),
            ],
        ),
    ]
