# Generated by Django 4.2.4 on 2023-10-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user_profile',
            new_name='student',
        ),
    ]
