# Generated by Django 4.2.4 on 2023-09-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup_Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('monday_starttime', models.TimeField(blank=True, null=True)),
                ('monday_endtime', models.TimeField(blank=True, null=True)),
                ('tuesday_starttime', models.TimeField(blank=True, null=True)),
                ('tuesday_endtime', models.TimeField(blank=True, null=True)),
                ('wednesday_starttime', models.TimeField(blank=True, null=True)),
                ('wednesday_endtime', models.TimeField(blank=True, null=True)),
                ('thursday_starttime', models.TimeField(blank=True, null=True)),
                ('thursday_endtime', models.TimeField(blank=True, null=True)),
                ('friday_starttime', models.TimeField(blank=True, null=True)),
                ('friday_endtime', models.TimeField(blank=True, null=True)),
                ('saturday_starttime', models.TimeField(blank=True, null=True)),
                ('saturday_endtime', models.TimeField(blank=True, null=True)),
                ('sunday_starttime', models.TimeField(blank=True, null=True)),
                ('sunday_endtime', models.TimeField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_availability', to='userregistration.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_appointments', to='userregistration.userprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to='userregistration.userprofile')),
            ],
        ),
    ]
