# Generated by Django 4.2.4 on 2023-09-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userregistration', '0002_expertise_userprofile_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expertise',
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertise',
            field=models.CharField(blank=True, choices=[('Visa Counselor', 'Visa Counselor'), ('Career Counselor', 'Career Counselor'), ('Migration Counselor', 'Migration Counselor'), ('Stress Counselor', 'Stress Counselor')], max_length=50, null=True),
        ),
    ]
